// actionTypes.js
export const FETCH_DISPENSERS_REQUEST = 'FETCH_DISPENSERS_REQUEST'
export const FETCH_DISPENSERS_SUCCESS = 'FETCH_DISPENSERS_SUCCESS'
export const FETCH_DISPENSERS_FAILURE = 'FETCH_DISPENSERS_FAILURE'
